### ISSUE TITLE
Feature request: add 'prec' for gpx output

### ISSUE THREAD

**Issue by twekkel** [gpsbabel/gpsbabel#1000]
gpsbabel already has 'elevprec' to limit the number of digits for elevation, but not for lon/lat. Would be great to have 'prec' too, as now gpx files somethimes blowup because to the (default?) of 9 digits.

**Comment by robertlipe** [comment]
You can easily modify the gox writer in your own copy. It's changing the
number at

https://github.com/GPSBabel/gpsbabel/blob/ac26579c67b15a867d606dd6b69d6640fa6ed9f4/gpx.cc#L77

**Comment by twekkel** [comment]
Thanks Robert, but it isn't very flexible. For now I will post-process with some sed/awk/perl/python as I want to remove more bloat from some of the GPX files I have.
