### ISSUE TITLE
[PATCH] Add example of using multiple filters

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1016]
At the bottom of
https://www.gpsbabel.org/htmldoc-development/filter_interpolate.html
mention that sometimes one cannot use multiple filters in the same command.

```
Example of combining interpolate and time filters:
We must use two invocations:

gpsbabel -i kml -f i.kml -o kml,points=0,lines=0,track=1 \
-x interpolate,time=1 -F - |
gpsbabel -i kml -f -     -o kml,points=1,lines=0,track=0 \
-x track,start=$A,stop=$B -F o.kml
```

(P.S., I bet you no user could get the above just right like I did without days of trial and error, just like I did.)

)(No, I can't make a pull request, because the documentation system is so fragmented that there are several files involved -- all hard to track down which one is best, and also this is more than just a one line example, so you will have to be sure it looks good yourself because I don't have all that docbook or whatever stuff installed. So sorry it is not a real [PATCH].)

**Comment by tsteven4** [comment]
Please provide a test case.  I can only guess this is an artifact of how kml maps to/from waypoints,routes and tracks.

**Comment by jidanni** [comment]
Your goal is to get the same position as in [my investigation](https://commons.wikimedia.org/wiki/File:Eastern_part_of_Tanaga_Island_Alaska.jpg#Summary) (where was the plane at at the given second,) but with only one invocation of gpsbabel, not two!

[time2position.sh.gz](https://github.com/GPSBabel/gpsbabel/files/10870667/time2position.sh.gz)
[FlightAware_UAL871_KSFO_RCTP_20221220.kml.gz](https://github.com/GPSBabel/gpsbabel/files/10870668/FlightAware_UAL871_KSFO_RCTP_20221220.kml.gz)

**Comment by tsteven4** [comment]
I don't know what version you are using, and I'm guessing at your time, but the straightforward serial application of the interpolate and track filter seems to work fine.

$ PATH=./bld:$PATH ./t2p.sh FlightAware_UAL871_KSFO_RCTP_20221220.kml 20221221032718
{{Location|51.667003|-177.816329}}
$ PATH=./bld:$PATH ./time2position.sh FlightAware_UAL871_KSFO_RCTP_20221220.kml 20221221032718
{{Location|51.667003|-177.816329}}

t2p.sh:
```
# $0 FlightAware_UAL871_KSFO_RCTP_20221220.kml 20221221032538
gpsbabel -i kml -f $1 -x interpolate,time=1 -x track,start=$2,stop=$2 -o kml,points=1,lines=0,track=0 -F - | tac |
    perl -nwle'
        if (/coordinates>([^<]+)/) {
            @F = split ",", $1;
            printf "{{Location|%s|%s}}\n", @F[ 1, 0 ];
            exit;
        }
'
```

**Comment by tsteven4** [comment]
You can also do this entirely in gpsbabel:
$ ./bld/gpsbabel -i kml -f FlightAware_UAL871_KSFO_RCTP_20221220.kml -x nuketypes,waypoints -x interpolate,time=1 -x track,start=20221221032538,stop=20221221032538 -o xcsv,style=x.style -F -
{{Location|51.599380|-177.425000}}

x.style:
```
# gpsbabel XCSV style file
DESCRIPTION     Comma separated values
#
# FILE LAYOUT DEFINITIIONS:
#
FIELD_DELIMITER         ""
RECORD_DELIMITER        NEWLINE
#
# INDIVIDUAL DATA FIELDS, IN ORDER OF APPEARANCE:
#
IFIELD CONSTANT, "{{Location|", "%s"
IFIELD LAT_DECIMAL,"","%f"
IFIELD CONSTANT, "|", "%s"
IFIELD LON_DECIMAL,"","%f"
IFIELD CONSTANT, "}}", "%s"
```

**Comment by jidanni** [comment]
Well that is all amazing.
I'm not sure if the docs have any examples of combing two -x's.
Anyway maybe on the page I mentioned it might be useful
to add and example "Get location of airplane at time T from track"

gpsbabel -i kml -f flight_track.kml -x interpolate,time=1 -x track,start=$T,stop=$T -o kml,points=1,lines=0,track=0

(Note we never mentioned what if we wanted sub-second positions.)

**Comment by robertlipe** [comment]
On Thu, Mar 2, 2023 at 6:49 PM 積丹尼 Dan Jacobson ***@***.***>
wrote:

> Well that is all amazing.
> I'm not sure if the docs have any examples of combing two -x's.
>
We do, but not really in a way that would show with a "command -F"

https://www.gpsbabel.org/htmldoc-development/Advanced_Usage.html

Want to use seven -i, -o it to file 1 for debugging, run a filter, -o it
for debugging, read another -i, then -o the whole thing a USB Garmin here,
-i yet another file, then -o to garmin on USB:2 ? Go for it. The syntax is
almost that literal. Things happen, in order, left to right. "... -o kml -F
kml1.kml" -x trackfilter,blah -F kml2.kml and then comparing kml1 and kml2
by toggling them in the left hand panel of Earth is a totally awesome way
to debug that trackfilter invocation.

We're kind of like objcopy
<https://sourceware.org/binutils/docs/binutils/objcopy.html>, dd,
ImageMagicks Convert <https://imagemagick.org/script/convert.php>, or
ogr2ogr <https://gdal.org/programs/ogr2ogr.html>: We have a head-exploding
combination of things you can do. Think of our GUI as Handbrake to ffmpeg
<https://ffmpeg.org/ffmpeg.html>. (That's underplaying the awesomeness of
Handbrake, though....) We simply cannot try to list examples for everything
and trying to do so actually makes it worse. We try to be DEscriptive in
giving information about each possible ingredient and telling the  ways
they can be mixed instead being of PREscriptive and providing the exact
keypresses. We can be crazy complicated. I know this. Sorry/notsorry. A few
people, like you (hopefully in about 20 minutes), have that "light bulb"
moment. 99.9% of our users never do more than convert single format A to
single format B.

If you want to apply for the bonus round, we have a feature that's so nerdy
that I may be the only one that uses it, and rarely at that. Look at our
Stack <https://www.gpsbabel.org/htmldoc-development/filter_stack.html>
Filter. You can come really close to poor-man's GIS (ala QGIS/Grass) levels
of nerdery. With that, you can see you can pull off some amazing things
from a single use and shouldn't need to piple our output back into our own
input and so on. (If you explore it, please don't break it. It's a bear to
debug. :-) )


Now that you're having that lightbulb moment (and I'm drowning in doc
technical issues in another windows) if you think you have enough special
little tips to share that are more than "add a comma after this...", write
them up for a page on https://www.gpsbabel.org/tips/ and we'll just pull
them into the man site.

Thanx for all your interest through the years!
RJL

**Comment by jidanni** [comment]
I see, on the tips page there should be a new link, tips for air travelers. Or tips for aviation or tips for airplanes or whatever. Okay and then on that new page called air.html or whatever, there should be, "Junior mapper Dan Jacobson has submitted a tip about..

**Comment by jidanni** [comment]
Okay, and then in my tip I'll make a story about how one was enjoying the hors d'oeuvres on a spanking new Boeing Dreamliner, when one realized that the electrostatic tinted glass windows blocked all GPS signals.

So how are we to 'geolocate' the photo that we took of the enemy spy base? The only thing useful in our Exif headers was just the time stamp. It was like we were using some camera from the turn of the century. You know 2000.

So where was that photo we took at 13:13:13 taken?...

**Comment by jidanni** [comment]
Okay, now off the plane we had directly to the FlightAware etc websites where they offer one whole week of KML flight tracks at no charge.

Then we just set the start and stop times to be the same and then plug it into this nifty formula.. ~~and voila, we were at the South Pole. Haha. only joking. We were at the East pole.~~

Anyway so perhaps you guys at GPSbabel headquarters could make that HTML framework and I'll just come in and make some final adjustments to that air.html. Thanks!

**Comment by GPSBabelDeveloper** [comment]
Remember to get that second photo with the label showing your sponsored
drink during hors d'oeuvre hour over the enemy base for your influencer
post. Please let your photograph be on your flight from Sydney to Santiago
that flies over Toronto that proves the electrostatic tinted glass windows
were provided by Big Globe™.

If you provide the prose for that, I'll absolutely make that part of the
GPSBabel canon. I've made everyone else mad at me today, so let's make it
everyone. Bring on the flat earthers from all over the globe!

(Limited time offer. Valid only to Dan.)

It's a bit funny that you mentioned EXIF support because just this week, I
was wondering if that's one of those things like the stack filter, sessions
support, or inifile support that seemed like a great nerd trick that got
put into our code but is never actually used by anybody in the real world.

**Comment by jidanni** [comment]
All I know is I was using Exiftool to get the stuff out of the Exif headers.
Dreamliner nightmare: https://www.google.com/search?q=dreamliner+gps+signals+windows
I'll submit some subdued HTML for you in a couple days.

**Comment by jidanni** [comment]
OK, I made [my own tip page on my own website](https://www.jidanni.org/comm/air/routes/programs/gps/tips.html), so I'll close this issue. Thanks!
