### ISSUE TITLE
Document "human readable" as a matter of opinion

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1039]
https://www.gpsbabel.org/htmldoc-development/style_define.html mentions
LAT_HUMAN_READABLE
LON_HUMAN_READABLE
LATLON_HUMAN_READABLE

In that file please also mention that "human readable" is in fact a
subjective concept, as some users believe that [Decimal degrees](https://en.wikipedia.org/wiki/Decimal_degrees) is much more readable than [DMS](https://en.wikipedia.org/wiki/Degree_(angle)#Subdivisions).

**Comment by robertlipe** [comment]
It works as per example, can be overridden, and humans are free to disagree. No further changes in this area are planned.
