### ISSUE TITLE
Allow -o unicsv,fields=...

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1042]
https://www.gpsbabel.org/htmldoc-development/fmt_unicsv.html says:

>fields option
>Name and order of input fields, separated by '+'.

>This option lets you specify the field names of your input file from the command line instead of relying on the first line of your input file describing the file. Field names are separated by a '+' character. The list of field names is exactly that allowed in the first line of a unicsv file without this option.

>Example 3.45. Example for unicsv fields option to describe input file.

>For example ... gpsbabel -i unicsv,fields=lat+lon+description -f file.csv -o gpx -F file.gpx declares that file.csv has three fields, latitude, longitude, and description, in that order.

OK that's great. But it would also be great if one could do the same for output. E.g., for -i kml -o unicsv it seems the default is
- No+Latitude+Longitude+Altitude+Date+Time .

Well, if we could do
- -o unicsv,fields=Latitude+Longitude+Altitude+Date+Time

we could e.g., shave off the No field, without needing to resort to awk, perl, or -o xcsv,style=file.style .

**Comment by jidanni** [comment]
Here the user should get an warning that "_fields_ has not been
implemented for _output_, at least yet!"
```
gpsbabel -i kml -f - -o unicsv,fields=no+latitude -F -
```

**Comment by robertlipe** [comment]
I'm not sure we want to duplicate Style in unicsv. They're different..

I do agree that should be an error. Now it is.

./gpsbabel -t -i unicsv -f /dev/null -x nuketypes,waypoints -o unicsv,fields=no+latitude -F z.csv

unicsv : option 'fields' is not supported on output
