### ISSUE TITLE
Eliminate duplicates from KML LineString

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1046]
See that ugly duplicate
```
        <Placemark>
          <name>Path</name>
          <styleUrl>#lineStyle</styleUrl>
          <LineString>
            <tessellate>1</tessellate>
            <coordinates>
120.864131,24.181809
120.864131,24.181800
120.864177,24.181781 HERE
120.864177,24.181781 HERE
120.864191,24.181781
120.864279,24.181854
120.864423,24.181854
120.864523,24.181895
120.864639,24.181847
120.864730,24.181707
</coordinates>
          </LineString>
        </Placemark>
```

Well https://www.gpsbabel.org/htmldoc-development/filter_duplicate.html
mentions some cures, but
```
gpsbabel -i kml -f - -x duplicate,location -o kml -F -
```
won't get rid of it. I had to use Unix `uniq(1)`.
So maybe `-x duplicate,location` needs to be strengthened "to fight even
stubborn duplicates hiding out in LineStrings."

**Comment by robertlipe** [comment]
Duplicates works on waypoints, not tracks.

You're looking for the simplify filter
https://www.gpsbabel.org/htmldoc-development/filter_simplify.html

I would consider a valid request (now that we can actually do it - when we
created this, it wasn't practical) is to add a parallel for count called
percent that looked at the number of points in each trac/route,
multiplied the count by percent, and then effectively ran the filter with a
count of that value. (That may not be quite how it works internally, but
something like that) Then uou could specify 99 for "keep the majority of
my million points but toss the lowest-hangng fruit keeping the fidelity of
the track" or "20" which would all but destroy your map, but keep any major
turnpoints.

**Comment by jidanni** [comment]
Well, the challenge is to
- remove only repeated exact copies of something in succession.
- but leave all other data exactly the same, like [uniq](https://www.gnu.org/software/coreutils/uniq) .

Yes, in theory error=0 of
https://www.gpsbabel.org/htmldoc-development/filter_simplify.html
might do the same but it might also affect other data. But I didn't test it.
