### ISSUE TITLE
Don't hardwire "to six decimal degrees" assumptions

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1048]
https://www.gpsbabel.org/htmldoc-development/filter_duplicate.html mentions
> that has the same coordinates (to six decimal degrees) as a waypoint

OK, but hardwiring such assumptions without giving the user a way to
override them is only asking for trouble later...

Sure, it might not matter for boating applications, but it might for
mini-golf.

**Comment by robertlipe** [comment]
I get your point that constants are bad, and you're not totally wrong, but we've served many, many millions of users without issue.  As a practical matter, we are "GPS"Babel and not "ProfessionalSurveyingEquipment"Babel.

Six digits gets below .4mm, which is on on the order of the thickness of a nice business card. I can live with that.
