### ISSUE TITLE
Filter by name

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1049]
Here, to remove any KML Placemarks whose names match `/parcel|wetland/`
we made this big rigmarole program containing:
```
my $x = XML::LibXML::XPathContext->new($dom);
$x->registerNs( k => 'http://www.opengis.net/kml/2.2' );
for ( $x->findnodes("//k:Placemark/k:name") ) {
    $_->parentNode->unbindNode if $_->findvalue(".") =~ /parcel|wetland/;
}
```
Yes, one does read that [duplicate_to_ignore](https://www.gpsbabel.org/htmldoc-development/filter_duplicate.html#duplicate_to_ignore) perhaps can also do something like that.
Maybe
```
echo north parcel > to_ignore.csv
```
would zap `<name>north parcel</name>` Placemarks.
If so, please add some KML examples to that document. Thanks.

**Comment by robertlipe** [comment]
The UI on that would be out of our scope. I think your php (or whatever that is... DOM is DOM) is a perfectly reasonable thing to do.

I sense that you're trying to make GPSBabel a GIS database and we're just not.
