### ISSUE TITLE
Idea: PROLOGUE AUTO

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1050]
Regarding [PROLOGUE](https://www.gpsbabel.org/htmldoc-development/style_layout.html), I got an idea!

- PROLOGUE AUTO

Which would mean to generate the prologue automatically, based on the
IFIELDs and FIELD_DELIMITER.

For instance,

```
RECORD_DELIMITER NEWLINE
PROLOGUE AUTO
FIELD_DELIMITER COMMA
IFIELD LAT_DECIMAL,,%f
IFIELD LON_DECIMAL,,%f
IFIELD GMT_TIME,,%H:%M:%S
IFIELD ALT_FEET,,%.0f
IFIELD PATH_SPEED_KPH,,%.1f
IFIELD PATH_COURSE,,%f
```
would be equivalent to

```
RECORD_DELIMITER NEWLINE
PROLOGUE LAT_DECIMAL,LON_DECIMAL,GMT_TIME,ALT_FEET,PATH_SPEED_KPH,PATH_COURSE
FIELD_DELIMITER COMMA
IFIELD LAT_DECIMAL,,%f
IFIELD LON_DECIMAL,,%f
IFIELD GMT_TIME,,%H:%M:%S
IFIELD ALT_FEET,,%.0f
IFIELD PATH_SPEED_KPH,,%.1f
IFIELD PATH_COURSE,,%f
```

but without the user needing to type everything twice, or often forgetting to
update the PROLOGUE every time he adds an IFIELD.

Sure, he could still do it the old way, if he doesn't want SCARY CAPS.
But when the result is e.g., going to be consumed by sqlite etc., why
force him to come up for names of fields that already have names?

You will note that I placed PROLOGUE AUTO before FIELD_DELIMITER,
that way the program can start gathering the information it needs at
the right time.

Yes, call it AUTOMATIC instead of AUTO. Whatever. Thanks.

**Comment by robertlipe** [comment]
I think you've covered this a few times tonight in different forms. I think you seek unicsv.

./gpsbabel -t -D9  -i gpx -f reference/track/seg2trk_test.gpx -o unicsv -F -

No,Latitude,Longitude,Altitude,Speed,Course,HDOP,Date,Time
1,47.421186,19.220939,152.0,0.00,0.0,2.00,2012/11/05,01:16:29
2,47.421095,19.220695,138.3,0.31,0.0,3.00,2012/11/05,01:17:37
[ ... ] 
No duplication of fields. No typing them out. No dealing with what if some records have them and some don't.

We probably don't describe it well enough (it shows that it's an afterthought after we described and fixed these issues many times)) but I really think that unicsv overcomes a bunch of issues with  style/INPUT, tabsep (using tabsep) csv (using (csv) and our style scheme in general.

Closed in favor of unicsv.

**Comment by jidanni** [comment]
No I think you are missing my point entirely.

I am saying style files are great.

They could be greater if they had one feature.

The feature is a way to keep the PROLOGUE line consistent with the fields one has inserted below it.

Just a way to make it simpler to maintain style files.

For those users who want PROLOGUEs that simply reflect the fields further down in the file.

Also, I want to add to my idea:

Here's how one could get arbitrary titles too:

Taking a idea from SQL: "AS":

` IFIELD PATH_COURSE,,%f AS Bearing`

This would put `Bearing` instead of `PATH_COURSE` into the header!

**Comment by GPSBabelDeveloper** [comment]
unicsv effectively writes the prologue for you.

Most people are writing files that need specific ordering. I don't think we
can dlegate that to auto.

I do geneerally think that styles are one of the best ideas we'e had, but
it's not like we have (or have ever had) people writing tons of style files.

**Comment by jidanni** [comment]
@GPSBabelDeveloper thanks, but for starters: #1042 .
