### ISSUE TITLE
Include field names in fmt_openoffice.html automatically

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1051]
When generating
https://www.gpsbabel.org/htmldoc-development/fmt_openoffice.html perhaps add
> Currently the header of the output file looks like:

and inject into the document the output of the following script:
```
gpsbabel -i openoffice -f /dev/null -o openoffice -F -|perl -pwle 's/\t/, /g'
```
which makes
> Index, Lat, , , Lon, , , Icon, Name, Description, Notes, URL, Link Text, Altitude (m), Distance (km), Speed (m/s), Course (°), Time, HDOP, VDOP, PDOP, Satellites, Fix

No, you don't even have to explain what the mystery blank fields are all about...
(which cause sqlite to say
> Columns renamed during .import due to duplicates:
"?" to "?_3", "?" to "?_4", "?" to "?_6", "?" to "?_7" )

Just put the fields into the document, so people can get an idea of what
will be in the output, even before (buying their own computer and)
installing and running the program.

Anyway, offline, let's figure out what the weird Time is. It must be one
of the items on
https://www.gpsbabel.org/htmldoc-development/style_define.html probably
_Excel time_ or something. This will take lots of trial and error to
figure out, because of the simple fact that it is not documented, here
offline.

**Comment by robertlipe** [comment]
Effectively a Duplicate of #1052

**Comment by tsteven4** [comment]
> Anyway, offline, let's figure out what the weird Time is. It must be one
> of the items on

Indeed, it is EXCEL_TIME.  See https://github.com/GPSBabel/gpsbabel/blob/master/style/openoffice.style

**Comment by robertlipe** [comment]
Closed. As described, unicsv is the right tool for this.
