### ISSUE TITLE
Make tabsep understandable offline

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1052]
https://www.gpsbabel.org/htmldoc-development/fmt_tabsep.html says

> For a list of fields, see the style/tabsep.style file in the GPSBabel source distribution

Well that's great. But it makes the whole thing unusable offline,
especially in the north woods without an Internet connection.

Therefore there should be an option to print a one line field name
header.

Then one wouldn't need the source code, even if it is the same version
as the program on disk.

Same problem with
https://www.gpsbabel.org/htmldoc-development/fmt_custom.html

And also, it would be nice to read about what fields one can see without
needing to run the command to find out. Useful for users comparing
programs via reading about them before deciding which to install.

Therefore, when generating these documents, have the currents set of
field name injected right in the document.

OK, so how can a user in the north woods use these commands now? By
reverse engineering what the fields mean... some look sort of like
somethings that we were trying very hard to compute in the first place,
sitting right under our nose, but without extensive testing we can't be
sure they are the same. A simple header strip would be the Rosetta Stone
in this case.

Also how are we going to import such a file to e.g., SQLite, without a
header strip? We would have to make up our own field names.

**Comment by robertlipe** [comment]
Tabsep is now much better done by the unicsv format, which is self-describing on output.

Tabsep was also requested by one GPSBabel user, a friend of mine from a former job, that's passed away. I'm sure tabsep (and openoffice) are out of date and should probably be dropped.

Steve, shall we nuke these?
