### ISSUE TITLE
Some KML folders are missing their names

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1057]
Here this Folder should have `<name>Route 1</name>`:

```
<Folder>
  <name>Routes</name>
  <Folder> <========== Mystery Folder
    <Folder>
      <name>Points</name>
```
Seen with:
> gpsbabel -i unicsv -f - -x transform,rte=wpt,del -o kml,trackdata=0 -F -

**Comment by robertlipe** [comment]
We don't support folders. There are literally hundreds of KML tags and concepts we dont support because they don't have any analog in common programs. 

In general, trying to make GPSBabel into a GIS database is going to result in frustration.

**Comment by jidanni** [comment]
Yes, there are no Folders upon input.
The program is making them.
It is making them for route1, route2, ... as many routes as there were in the input.
But it is forgetting to put their names on them.

It's like a parent who is having babies, but forgetting to give them names.
