### ISSUE TITLE
Need --fail-if-any-warnings option

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1083]
There should be a way to make gpsbabel exit 1 after these:
```
Arc filter: Warning: Arc file contains unusable vertex on line 1.
Arc filter: Warning: Arc file contains unusable vertex on line 2.
Arc filter: Warning: Arc file contains unusable vertex on line 3.
Arc filter: Warning: Arc file contains unusable vertex on line 4.
Arc filter: Warning: Arc file contains unusable vertex on line 5.
```
I.e., with `--fail-if-any-warnings` just remember upon exit to exit 1, not
exit 0.

I mean I am doing

```
if gpsbabel ... ; then launch the_rocketship; fi
```
and there's no way to stop it despite ~~errors~~ warnings.

- sqlite has --bail.
- perl has use warnings FATAL => q(all);
- curl has --fail and --fail-early
- gpsbabel has..... (freight train with oops, no brakes in the 3rd caboose.)

Sure, it fails for "serious" problems. But one man's serious is another man's curious. So there needs to be a way to fail for all of them.

**Comment by robertlipe** [comment]
You could rebuild with that call to Warning() replaced with a call to
Fatal(), but I'm not sure we want to make it a general error.

**Comment by robertlipe** [comment]
Options given. You're free to monitor stderr (stdout? I forget) and take further actioni on your own malformed input. No further changes here are planned.
