### ISSUE TITLE
Problem converting kml with large number of coordinates to osm

### ISSUE THREAD

**Issue by krzyk** [gpsbabel/gpsbabel#1098]
I have a kml file that has a bit of coordinates ([sq.zip](https://github.com/GPSBabel/gpsbabel/files/11374511/sq.zip)) and I would like to convert it to osm.
I tried following command line:
```
gpsbabel -i kml -f sq.kml -o osm,tag=highway:primary -F tiles.osm
```

But all I get is an almost empty tiles.osm file with just the main tag.
I tried with `-D 5` option (the docs miss what values can be put there so I tried with `5`), but didn't get any errors, I'm not sure what I'm doing wrong, or such file is maybe unsupported?

When I upload that kml file to online tools it shows the correct data on maps.

**Comment by tsteven4** [comment]
This looks like a bug.  We ignored the /Polygon/outerBoundaryIs/LinearRing/coordinates because it was inside a MultiGeometry which is a bug.  We always ignore Polygon/innerBoundaryIs, I'm not sure what we would do with this anyway.

Do you like this one better?

[tiles.osm.gz](https://github.com/GPSBabel/gpsbabel/files/11374744/tiles.osm.gz)

**Comment by krzyk** [comment]
@tsteven4 Thanks, this looks much better, but the shape doesn't have holes, which are there in the kml file.

I checked kml file in google earth and osm file in JOSM.

**Comment by tsteven4** [comment]
yes, we ignore the innerBoundaryIs/LinearRing elements.

We support waypoints, routes and tracks, not arbitrary GIS shapes.  The outerBoundaryIs/LinearRing elements are mapped to tracks.

**Comment by tsteven4** [comment]
This one converts both the inner and outer boundaries to tracks.  Does that work better for you?  What tool are you using to view these osm files?
[tiles2.osm.gz](https://github.com/GPSBabel/gpsbabel/files/11377272/tiles2.osm.gz)

**Comment by krzyk** [comment]
That one looks great. Thanks.

I use JOSM to view osm files.
