### ISSUE TITLE
Say "No valid input type specified before input filename."

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1121]
```
$ gpsbabel -f e.csv -i csv -o kml -F g.kml
No valid input type specified
```
That error message is wrong.

The user did specify a valid input type.

The error message should say:

```
No valid input type specified before input filename.
```

And the same is needed for the output case.

See also #1120.

**Comment by robertlipe** [comment]
We already document that arguments are processed left to right. This is really fundamental to the way we work.

https://www.gpsbabel.org/htmldoc-1.8.0/Invocation.html#:~:text=Options%20are%20always%20processed%20in%20order%20from%20left%20to%20right.
