### ISSUE TITLE
igc compile warning

### ISSUE THREAD

**Issue by tsteven4** [gpsbabel/gpsbabel#1131]
clang++ 14 is giving

`igc.cc:257:7: warning: variable 'current_line' set but not used [-Wunused-but-set-variable]
  int current_line = 1; // For error reporting. Line numbering is off by one for some reason.`

Also note it is incremented in another line.

@PacketFiend can you fix this, if you like add it to #1060.  thanks

**Comment by PacketFiend** [comment]
Fixed in https://github.com/GPSBabel/gpsbabel/pull/1060/commits/b3fcce8d9d06ea398368f62dfaa3b0574affcbdb

I was meaning to include this debug output but missed it.

**Comment by PacketFiend** [comment]
#1060 has been merged so this can be closed.
