### ISSUE TITLE
:error:fetch Failed to fetch curl-ca-bundle: The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by ishandutta2007** [gpsbabel/gpsbabel#1159]
Trying to install `gpsbabel` on macos 10.13 via macports.

 ```sudo port install gpsbabel```

Error:

```

:notice:fetch --->  Attempting to fetch curl-7.72.0.tar.xz from http://nue.de.distfiles.macports.org/curl
:debug:fetch Fetching distfile failed: The requested URL returned error: 404 Not Found
:notice:fetch --->  Attempting to fetch curl-7.72.0.tar.xz from http://aarnet.au.distfiles.macports.org/pub/macports/distfiles/curl
:debug:fetch Fetching distfile failed: The requested URL returned error: 404 Not Found
:error:fetch Failed to fetch curl-ca-bundle: The requested URL returned error: 404 Not Found
:debug:fetch Error code: NONE
:debug:fetch Backtrace: The requested URL returned error: 404 Not Found
:debug:fetch     while executing
:debug:fetch "error $lastError"
:debug:fetch     (procedure "portfetch::fetchfiles" line 66)
:debug:fetch     invoked from within
:debug:fetch "portfetch::fetchfiles"
:debug:fetch     (procedure "portfetch::fetch_main" line 17)
:debug:fetch     invoked from within
:debug:fetch "$procedure $targetname"
:error:fetch See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_curl/curl-ca-bundle/main.log for details.
```

**Comment by robertlipe** [comment]
The inability to fetch curl has nothing to do with us. Sorry. Take that up
with your os vendor.

...or just go to our own download page at www.GPSBabel.org

**Comment by ishandutta2007** [comment]
> The inability to fetch curl has nothing to do with us. Sorry. Take that up

@robertlipe that file doesn't even exist, it's not a network issue.

**Comment by ishandutta2007** [comment]
> ...or just go to our own download page at [www.GPSBabel.org](http://www.GPSBabel.org)

@robertlipe I need for macos 10.13. The version GPSBabel1.8.0.dmg which is available on website supports macos 10.14+.

**Comment by GPSBabelDeveloper** [comment]
Your error says you can't fetch curl from somewhere in Aus. That's not us
issuing or serving that.

Your is may be so old it's just not supportable any longer. The wheels on
MacOS turn pretty relentlessly.

**Comment by ishandutta2007** [comment]
@GPSBabelDeveloper How to install GPSBabel on macos 10.13 (High Sierra)?

**Comment by ishandutta2007** [comment]
@GPSBabelDeveloper I do understand that you are in no way responsible for file hosted by macports, and I do I understand that it may not be an issue of this repo. I am just looking for solution for my problem, and you guys seem to be the closest ones who can help.  🥇 

To give bit more context I am trying to install GPSBabel as part of setting up https://github.com/ncssar/gpsio
