### ISSUE TITLE
www.gpsbabel.org doesn't contain a link to github page

### ISSUE THREAD

**Issue by daald** [gpsbabel/gpsbabel#1184]
I just browsed through the official website https://www.gpsbabel.org/, looking for the source code. There is a lot of documentation (which I appreciate), three binary downloads, and many more, but finally I had to google for the source code to find this github project. If the link is somewhere, it is very very hidden. Why?

I would like to see a link to the github project somewhere on the first page.

**Comment by robertlipe** [comment]
It's on the download page: https://www.gpsbabel.org/htmldoc-development/Source.html
It's no the building from soure page: https://www.gpsbabel.org/download.html
It's the first hit from any search engine.
It's been found by hundreds of people a week for years.

**Comment by daald** [comment]
[THIS](https://www.gpsbabel.org/download.html) is the download page.
And somewhere in the paragraph "GPSBabel is free software" of the main page would also be helpful.

I'm just telling my user experience. It took me 5 minutes what should be 20 seconds.

**Comment by GPSBabelDeveloper** [comment]
[image: Screenshot 2023-09-22 at 6.10.11 PM.png]
