### ISSUE TITLE
garminextensions option (-o gpx,...) removes <speed> from output file

### ISSUE THREAD

**Issue by jan-gerard** [gpsbabel/gpsbabel#1188]
I noticed that when converting to a gpx file from a .fit file (for example) that contains speed data, it is correctly parsed to the output file. But when I specify the garminextensions option in the -o gpx option, the speed data is omitted. Meanwhile, other data, like heartrate, is included, but still speed is missing. I cannot found any combination of parameters that seems to work, so I assume this is a small bug.

`.\gpsbabel.exe -t -i garmin_fit -f run.fit -o gpx,garminextensions -F run2.gpx`

In the first case, I get as output for example 

```    
<trkpt lat="53.350419521" lon="5.616662057">
      <ele>29.8</ele>
      <time>2023-01-01T19:32:58Z</time>
      <speed>1.53</speed>
</trkpt>
```

and in the second case, I get more data, but no speed field.

```
      <trkpt lat="53.350419545" lon="5.616662060">
        <ele>29.800</ele>
        <time>2023-01-01T19:32:58Z</time>
        <extensions>
          <gpxtpx:TrackPointExtension>
            <gpxtpx:atemp>28.000000</gpxtpx:atemp>
            <gpxtpx:hr>104</gpxtpx:hr>
            <gpxtpx:cad>56</gpxtpx:cad>
          </gpxtpx:TrackPointExtension>
        </extensions>
      </trkpt>
```

Or is there a way to fix this easily?

**Comment by robertlipe** [comment]
GPX 1.1 does not have a speed tag and the extensions you're using force 1.1

Yes, this is widely acknowledged as an oversight in the GPX spec, but those
are the rules we have to play by.

The good news is that for the huge majority of devices, "speed" as a
distinct tag is almost never actually necessary'useful as it's computed via
successive timestamped location points.

**Comment by tsteven4** [comment]
Note that we will write the speed element for gpx 1.0.  You can force gpx 1.0:
.\gpsbabel.exe -t -i garmin_fit -f run.fit -o gpx,garminextensions,gpxver=1.0 -F run2.gpx
