### ISSUE TITLE
1.9.0 GUI pop up "Invalid return data at line 1 ..."

### ISSUE THREAD

**Issue by tsteven4** [gpsbabel/gpsbabel#1189]
This is with our just released 1.9.0 on macOS 13.6.  I am guessing this is some kind of update check error.

![image](https://github.com/GPSBabel/gpsbabel/assets/13596209/40f126f6-e768-43df-88f3-d16b767511f6)

**Comment by tsteven4** [comment]
upgrade.cc:
https://github.com/GPSBabel/gpsbabel/blob/007c0c1ac64daede1df9454335fb9129ef4e7e57/gui/upgrade.cc#L267-L277

**Comment by tsteven4** [comment]
The same pop up appears on Windows 11.

**Comment by GPSBabelDeveloper** [comment]
Sorry. Late night debug check that didn't get whacked. Fixed now.
