### ISSUE TITLE
jeeps bug?

### ISSUE THREAD

**Issue by tsteven4** [gpsbabel/gpsbabel#1220]
Jeeps was introduced in bb94c57 in 2002.  At that time gpssend.c had a function GPS_Make_Packet, which included parameters UC data and int16 n.  Presumably n is the number of unsigned characters in data.

Why is n being compared to DLE (#define DLE 0x10), which one would assume is the Data Link Escape ASCII character?

https://github.com/GPSBabel/gpsbabel/blob/bb94c57ceec13cd8450f842ccbf70d1cca76b8c6/gpsbabel/jeeps/gpssend.c#L62-L66

Today this has led to a similar comparison:
https://github.com/GPSBabel/gpsbabel/blob/66fa37eb30c3a2739b4dedb22c76290575297b16/jeeps/gpssend.cc#L61-L64

**Comment by tsteven4** [comment]
This sounds like "DLE stuffing" as described in the Garmin Device Interface Specification.

**Comment by robertlipe** [comment]
Right. That spec didn't exist (outside Olathe) at the time.

I remember there was some weirdness in the USB implementation. It's not
necessary at the bus level, but I can't remember if they faithfully
mimicked this in USB or not. So there may be some related goofy - looking
code in the USB side, too.
