### ISSUE TITLE
GPS serial memory leak?

### ISSUE THREAD

**Issue by tsteven4** [gpsbabel/gpsbabel#1221]
GPS_Serial_On allocates memory for the device header on both windows
https://github.com/GPSBabel/gpsbabel/blob/ad23c5767a149e71381503810677ba75df95c471/jeeps/gpsserial.cc#L94-L100
and posix
https://github.com/GPSBabel/gpsbabel/blob/ad23c5767a149e71381503810677ba75df95c471/jeeps/gpsserial.cc#L573-L575

GPS_Serial_Off frees the memory on windows
https://github.com/GPSBabel/gpsbabel/blob/ad23c5767a149e71381503810677ba75df95c471/jeeps/gpsserial.cc#L164-L169
but not posix.
https://github.com/GPSBabel/gpsbabel/blob/ad23c5767a149e71381503810677ba75df95c471/jeeps/gpsserial.cc#L599-L608

**Comment by robertlipe** [comment]
Back at home where I can review on something bigger than a phone...

It's probable that the obvious one-line fix is the correct one.

It's *possible* that it'll corrupt memory in some weird way. The serial/USB
paths have not been subject to the valgrind/memtest rigor that has
tormented the rest of the code. In addition to being a pain to run via
automation, the reality is that the runs are necessarily shorter (I think
even now that the biggest garmin won't take more than 1,000 wpts through
the USB protocol. Maybe it's 5,000.) and are less likely to be tied up in a
long-running daemon process than the rest of the code. Code touches the
device, moves data through, exits. A leak just isn't a big deal.

I think I brought on the devh stuff as part of the USB work in '04 or so.
It was definitely retrofitted in with a big hammer, even then.

If you want to go ahead and just add the "obvious"   xfree(dh); go for it.
If there's a problem, assign this to me and I'll find and attach a serial
and/or USB device and track down any exposed issue.

I'd respect you no less for just backing
<https://media2.giphy.com/media/COYGe9rZvfiaQ/giphy.gif?cid=ecf05e47afm9dzbthsmbzrymgmtckb4sovwcwiu0zuh55wil&ep=v1_gifs_search&rid=giphy.gif&ct=g>
away.

RJL

**Comment by tsteven4** [comment]
Thanks for your reply.  The leak is confirmed.
![image](https://github.com/GPSBabel/gpsbabel/assets/13596209/b8842c7a-2b4d-4453-8a63-8c2932c65a16)
