### ISSUE TITLE
Broken link to Entire Manual as PDF

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#1224]
1. On https://www.gpsbabel.org/readme.html
2. Click [Entire Manual as PDF](https://www.gpsbabel.org/htmldoc-development/gpsbabel.pdf)

**Comment by tsteven4** [comment]
Yes, the links are broken.  However, the material for the latest release is on the server:
https://www.gpsbabel.org/htmldoc-1.9.0/index.html
https://www.gpsbabel.org/htmldoc-1.9.0/gpsbabel-1.9.0.pdf

**Comment by robertlipe** [comment]
Links  (mostly) fixed. Old versions retired. 1.9.0 added.

I know release notes are missing.

**Comment by tsteven4** [comment]
perhaps we can write release notes as we do commits, or flag commits worthy of mention when we commit them.

**Comment by GPSBabelDeveloper** [comment]
I just added a tag for needs-release-notes.  We can apply it via the web
interface to either the issue or the PR.

Let's give that a try. Maybe that'll make creating the notes less dreadful.
