### ISSUE TITLE
Please restore compegps format

### ISSUE THREAD

**Issue by Nathagamelle** [gpsbabel/gpsbabel#1252]
Hi

We are stuck on an old version of gpsbabel, as our install base is compegps format, still widely used, still supported by GPSDump and others

GPSBabel is a conversion program. Please reconsider and if possible do not retire deprecated formats, converting to and from them are GPSBabel's raison d'être

thanks and a happy new year

**Comment by robertlipe** [comment]
We notified of intent to remove over a year before we did. Nobody stepped in to maintain it, so we shed little or unused formats so we could focus on keeping the remaining code alive.

The source code remains in Git and you're free to roll back, build, and support old versions. We simply lack the resources to do so.
