### ISSUE TITLE
Is there somewhere to download old exe files?

### ISSUE THREAD

**Issue by jwidness** [gpsbabel/gpsbabel#1254]
I'm looking to download 1.6.0, the last version to support mps files. Is there somewhere I can find an exe?

**Comment by GPSBabelDeveloper** [comment]
No.

One we quit supporting a version, we no longer distribute it as that
doesn't actually lighten our support load as people then ask us about the
very things we turned down.

**Comment by jwidness** [comment]
Do you have any ideas how I can get data out of some old mps files?
