### ISSUE TITLE
[feature request] Older Versions Download

### ISSUE THREAD

**Issue by BrianSwift** [gpsbabel/gpsbabel#1269]
I didn't see a way to download older pre-built versions.
My particular interest is the most recent MacOS version that supports Wintec TES files.

**Comment by robertlipe** [comment]
We don't support obsolete versions. We announced plans to drop this about two years before we did and there was no remaining users or volunters to maintain it and the cost of relatively unused (even if not zero) formats was blocking our forward progress.

The source is always available to anyone that wants to build and support older versions.
