### ISSUE TITLE
Style constant CR incorrectly mapped for style files

### ISSUE THREAD

**Issue by crispyjones** [gpsbabel/gpsbabel#1281]
Not possible to use the CR (carriage return) constant in custom style file as it is mapped to \n instead of \r

https://github.com/GPSBabel/gpsbabel/blob/15d3d22d85faf595e4ae05e34dc6b598c6637277/xcsv.cc#L170

**Comment by tsteven4** [comment]
Thanks.  That error had been present since the xcsv format was introduced in 2003! https://github.com/GPSBabel/gpsbabel/commit/56bd460f3
Will fix shortly.
