### ISSUE TITLE
A lot of bugs reported on Debian

### ISSUE THREAD

**Issue by jidanni** [GPSBabel/gpsbabel#133]
Have a look.
http://bugs.debian.org/cgi-bin/pkgreport.cgi?package=gpsbabel

**Comment by GPSBabelDeveloper** [comment]
If you would like to go through their bugreport system and find what's pertinent, and report back to them and/or us, awesome. Triaging old reports is helpful. At a glance, I see some really vague issues from years ago, including things we don't even ship, so I can't really tell they're tracking their system much at all.

If you have a bug, reporting it here or our mailing list (with version numbers, reproducible test cases, etc) is more likely to get attention.  We don't monitor everyone else's lists and systems.
