### ISSUE TITLE
Man page lacks basic usage examples

### ISSUE THREAD

**Issue by jidanni** [GPSBabel/gpsbabel#134]
Please add examples to the man page.
Yes, even if they are already in file:///usr/share/doc/gpsbabel/gpsbabel.html . Indeed, just
```
$ gpsbabel -i gpx -f /tmp/g.gpx -o kml -F /tmp/g.kml
```
would be fine.

**Comment by GPSBabelDeveloper** [comment]
Hi, and welcome.

We don't provide man pages because "basic usage" with our hundreds of formats and filters just doesn't work. Basic invocation is covered at https://www.gpsbabel.org/htmldoc-1.5.4/Invocation.html We have hundreds of pages of doc (!) at https://www.gpsbabel.org/readme.html
