### ISSUE TITLE
icon from csv to kml and gpx

### ISSUE THREAD

**Issue by Mannshoch** [GPSBabel/gpsbabel#181]
I use a csv and [mapbox/leaflet-omnivore](https://github.com/mapbox/leaflet-omnivore) to fead a online map with gsp points. Now I wish to convert  these data to KML for google maps and GPX for Osmand.  but how do I get a icons/Color to these file? I need two random to separate two kind of points.
For kml I tried to use a url but it does not replace the default from google in kml. In gpx I do not know how to insert an icon/color.

**Comment by GPSBabelDeveloper** [comment]
You can pass through a URL and we'll put it in <description> where Earth will linkify it.
$ cat /tmp/example.txt
lat, lon, color, url
36, -86, red, https://www.gpsbabel.org
$ ./gpsbabel -i unicsv -f /tmp/example.txt -o kml -F - | tail
        <snippet/>
        <description>https://www.gpsbabel.org</description>
        <styleUrl>#waypoint</styleUrl>
        <Point>
          <coordinates>-86.000000,36.000000</coordinates>
Honestly, if you're looking to craft stylized KML, we're probably not the right tool for you. Full KML is crazy complicated with multiple camera views and a cascading style scheme so you can change colors or size depending on hover state and lots of other things way beyond simple GPS converion tasks, which is what we do.
You may be looking for something more like Grass or QGIS or the features in Earth Pro to stylize your data. Each of those tools may use us for some of the conversion tasks, but they can do a better job for "color this red if population > N" sorts of tasks. Enjoy.
