### ISSUE TITLE
All EXIF Lat/Lon writes fail with "Aborted"

### ISSUE THREAD

**Issue by alanbur** [GPSBabel/gpsbabel#19]
I'm attempting to write Lat/Lon values from a waypoint file into the EXIF section of a JPEG file. All attempts fail with "Aborted" being printed on stdout, no other error is reported. Strace of the gpsbabel executable reveals that it is calling the libc abort() function which is causing the process to be terminated with SIGABRT.

The offending line seems to be this: https://github.com/gpsbabel/gpsbabel/blame/master/exif.cc#L1393

From looking at the odd indentation and the other changes made in the same commit (https://github.com/gpsbabel/gpsbabel/commit/847718da4591488afbd3c2f7270cc3b28df4576d) I'm guessing this was added for debugging and not removed before commit.

This needs fixing as it looks like it prevents any write operations to JPEG files.

**Comment by GPSBabelDeveloper** [comment]
Steven fixed this in Jan. It'll be included in the next release.
