### ISSUE TITLE
Warnings! Warnings! Warnings!

### ISSUE THREAD

**Issue by rickrich** [GPSBabel/gpsbabel#208]
Even though -Wall is specified!

[xxx.txt](https://github.com/gpsbabel/gpsbabel/files/2138386/xxx.txt)

**Comment by GPSBabelDeveloper** [comment]
Thanks, Rick. Hundreds, perhaps thousands,. of possible warnings in combinations of compilers and OSes have been addressed in 1.6.0.  if any remain for you, please attach them here but I'm going to close this for now.

**Comment by rickrich** [comment]
$ make > xxx.txt 2>&1
[xxx.txt](https://github.com/gpsbabel/gpsbabel/files/3101581/xxx.txt)
