### ISSUE TITLE
"Short GSA sentence" warning

### ISSUE THREAD

**Issue by fbonzon** [GPSBabel/gpsbabel#24]
I upgraded to GPSBabel 1.5.3 and now see thousands of "Short GSA sentence" warnings.

Raw NMEA output of Samsung Galaxy S5 phone:

```
$GPGSA,A,2,05,12,13,15,17,18,19,20,24,28,30,,0.9,0.7,0.7*30
$GNGSA,A,2,05,12,13,15,17,18,19,20,24,28,30,,0.9,0.7,0.7*2E
$GNGSA,A,2,69,70,71,73,79,80,,,,,,,0.9,0.7,0.7*28
$BDGSA,A,2,,,,,,,,,,,,,0.9,0.7,0.7*2B
```

nmea.cc now emits this "Short GSA sentence" warning (since July 2015) when there are less than 2 IDs (of SVs used in position fix) in a GSA sentence.

My BDGSA sentences have no satellite IDs (talker ID "BD" means Beidou constellation?), presumably because there were none visible (I was indeed far away from China).

Also seen in the NMEA log, when no satellites are visible in any constellation:

```
$GPGSA,A,1,,,,,,,,,,,,,,,*1E
$GNGSA,A,1,,,,,,,,,,,,,,,*00
$BDGSA,A,1,,,,,,,,,,,,,,,*0F
```

I don't consider these cases bad data and worth a warning, and suggest to change:

``` c
  if (scn < 4) {
```

to:

``` c
  if (scn < 2) {
```

on [this line](https://github.com/gpsbabel/gpsbabel/blob/7691a33ca73a9b9072b6e2598a90479f483d9e8c/nmea.cc#L694). May I proceed with PR?

**Comment by robertlipe** [comment]
Good call. Fixed in 0485397..585451c  Thanx!
