### ISSUE TITLE
Data lost with erase=1 and basic filesystem error

### ISSUE THREAD

**Issue by MattBlissett** [GPSBabel/gpsbabel#333]
> GPSBabel Version 1.5.4

This seems a surprising oversight, so I hope my data is just in some temporary folder -- although I can't find it.

```
sudo gpsbabel -i skytraq,baud=115200,erase=1 -f /dev/ttyACM0 -o gpx -F ~/France/20190331.gpx      
Cannot open '/home/matt/France/20190331.gpx' for write.  Error was 'No such file or directory'.
```

I'd forgotten to create the ~/France directory, but the GPS logger seems to have been erased anyway.

**Comment by robertlipe** [comment]
Sorry to be the one to dash your hopes, but your data is gone. I was
reluctant to add that 'erase' option for that very reason. It's a
destructive operation and by the time we encounter any problems on output
(we document that we do things strictly left to right and we mean that - by
the time the GPX file writer has opened the file, the skytraq reader had
already finished with the read and the erase - in that order) it's too late.

It was also an awkward fit for us from the start that we do conversions and
transfers and logger management, including erasures, really is an awkward
case.

Sorry. This is the way if fundamentally works and changing it to recover
this case it isn't practical.

RJL
