### ISSUE TITLE
OS X command-line binary

### ISSUE THREAD

**Issue by hugovk** [GPSBabel/gpsbabel#37]
The [download page](http://www.gpsbabel.org/download.html) says:

> For 10.9 (Mavericks), 10.8 (Mountain Lion), 10.7 (Lion), 10.6 (Snow Leopard), and maybe 10.5 (Leopard). This is a .dmg that contains the GUI and a binary for GPSBabel.

But when I download GPSBabel-1.5.3.dmg it only contains GPSBabelFE, the UI. 

Where can I find a command-line binary for OS X?

**Comment by robertlipe** [comment]
The GUI includes the CLI version.  /Applications/GPSBabelFE.app/Contents/MacOS/gpsbabel
