### ISSUE TITLE
gpsbabelfe "Translation options" lights not shown

### ISSUE THREAD

**Issue by cjmayo** [GPSBabel/gpsbabel#389]
If I run `gpsbabelfe` (with my default LANG environment variable, set to en_GB.utf8) I see the light symbols against the Waypoints, Routes and Tracks check boxes.

But if I run `LANG=de_DE gpsbabelfe` I just see "hyphens" in line with the bottom of the check boxes. Changing the Input Format using the combo box causes the lights to be displayed.

Starting values

Input Format: GPX XML
Output Format: Alan Map500 Waypoints and Routes (.wpr)

This is on GPSBabel 1.6.0 plus the patches for translations.
I don't see it on GPSBabel 1.5.4 - the Gentoo installation with translations in /usr/share/gpsbabel and without the code modified to load them.

**Comment by tsteven4** [comment]
Thanks.  I can reproduce this.  Please open an issue on github.

**Comment by tsteven4** [comment]
That was a great find, thanks @cjmayo for noticing and reporting it.

**Comment by tsteven4** [comment]
This was fixed by #390
