### ISSUE TITLE
Mention GitHub on www.gpsbabel.org

### ISSUE THREAD

**Issue by jidanni** [GPSBabel/gpsbabel#404]
https://www.gpsbabel.org/ should mention https://github.com/gpsbabel/gpsbabel somewhere.

**Comment by GPSBabelDeveloper** [comment]
https://www.gpsbabel.org/htmldoc-development/Source.html
https://www.gpsbabel.org/partners.html

**Comment by jidanni** [comment]
OK but I was thinking of e.g., "Helping us"
https://www.gpsbabel.org/contribute.html
right there in the top level menu.
