### ISSUE TITLE
Feature request: Upload garmin custom icons

### ISSUE THREAD

**Issue by fancsali** [GPSBabel/gpsbabel#421]
It'd be a great feature if we could not only use the built in symbols, but fetch/upload the actual bitmaps from the slots.

**Comment by robertlipe** [comment]
Garmin protocol specs never documented transfer of the icons. I've seen some third party software that can successfully modify the icons, so I know it can be done, but that's not really a conversion task.
Barring a contributor with a patch to deliver this, this is very unlikely to get traction in the current developer pool. It's just too esoteric and too far from our task of converting location data. Sorry.
