### ISSUE TITLE
FIT to GPX conversion ignores base time and provides times in 1989

### ISSUE THREAD

**Issue by ajmas** [GPSBabel/gpsbabel#54]
When I try converting a Garmin FIT file to GPX I find all the times in the file are in 1989, rather than the date recorded.

Looking at the specification, it would seem that we should probably be reading the time_created value in the file_id message and adding that to the timestamp value, if timestamp is less than 0x10000000.

Command line:

`gpsbabel -i garmin_fit -f "2016-09-09-10-29-53.fit" -o gpx -F 2016-09-09-10-29-53.gpx`

I can provide data files on request (about 1Mb in size for the .fit).

Was testing with gpsbabel 1.5.3_1, installed with MacPorts, on MacOS X 10.12

Looking at the 'D00001309 FIT File Types Description Rev 2.1' in the FitSDKRelease_20.10.01, for specs.

**Comment by GPSBabelDeveloper** [comment]
The license for the FIT SDK isn't compatible with open source projects like ours. (At least it wasn't when I last looked.) We have a fair number of .fit users, so it seems odd that this is totally broken.  If you can provide a detailed textual description of how to make this better, why your fit files are different than the ones we have, perhaps referencing https://github.com/gpsbabel/gpsbabel/blob/master/garmin_fit.cc (hint: search for 'timestamp') perhaps someone can take a swing at improving it.

**Comment by dark** [comment]
This was fixed by PR #75 too.
