### ISSUE TITLE
Respect empty KML <name>s upon conversion

### ISSUE THREAD

**Issue by jidanni** [GPSBabel/gpsbabel#555]
https://github.com/viking-gps/viking/issues/90 turns out to be a gpsbabel issue.

**Comment by GPSBabelDeveloper** [comment]
Working as intended.

We're a file converter. There are several places in many formats that a name may appear. We don't know which is going to be read by reader, so we populate many of them to ensure the user isn't met with blank fields.

I'd consider adding a global option to disable this, but in general, we default to being as helpful as we can be.
