### ISSUE TITLE
Garmin Virb 360

### ISSUE THREAD

**Issue by bloigge** [GPSBabel/gpsbabel#590]
Hi all,

We are using the garmin virb 360 in our tool for displaying 360° videos in a web-mapping application. Therefore we are converting the garmin fit-files into gpx using gpsbabel. This works as expected.

The problem we are facing currently is, that we need to find the exact timestamp when the video was recorded, so we can filter the track parts from one fit / gpx-track for each video file. 

To get the starting timestamp from one video file, we are using a lib called mediainfo, which extracts the metadata from the video like "Encoded_Date":"UTC 2020-06-03 15:46:40". Unfortunately this timestamp is not the exact timestamp the recording started.  It looks like there is no standard metadata tag for this timestamp.

Somehow Garmin Virb Edit is able to find the correct timestamp and map each video to the correct position on the track. So I guess there must be some kind of metadata stored in the fit-track which refrence the starting timestamp of the video. 

Am I right with my assumption? If so, is there a way to extract this data using gpsbabel?

**Comment by tsteven4** [comment]
It is entirely possible a more precise timestamp is included in the fit file.  There are many parts of fit files we don't understand.  I don't think we know how to extract any sub-second time information from a fit file.

**Comment by robertlipe** [comment]
I'm confirming that the only thing so far reverse engineered inside the fit code are 32-bit timestamps that do no include sub-second timestamps.

I have little doubt that a Virb 360 stores lots of data like camera pose, pitch, roll, brightness, frame index, and other zany things that don't map well to our fundamental core concepts of things we convert.

Indexing frame offsets in a video to a trackpoint is something that our Subrip module would probably like to know more about, too, but it really is outside our scope of development.
