### ISSUE TITLE
Issue with unicsv; invalid latitude, invalid lat

### ISSUE THREAD

**Issue by openclipboard** [GPSBabel/gpsbabel#591]
From the Windows version 1.6.0

Given a simple file:

```
description, name, lat, lon
a_jpg,a,40.10,-71.10
b_jpg,b,40.20,-71.20
c_jpg,c,40.30,-71.30
```

The command:

`"C:\Program Files (x86)\GPSBabel\gpsbabel.exe" -i unicsv,fields=description+name+lat+lon -f test.csv -o gpx -F test.gpx`

returns the error:

`'unicsv' Invalid latitude 1.66667e+23 in waypoint "name"`

**Comment by tsteven4** [comment]
The intent was you either have a header line in the file that defines the fields, or you use the fields option, but not both.
``` 
./gpsbabel -iunicsv -f test.csv
40.100000N 71.100000W a/a_jpg
40.200000N 71.200000W b/b_jpg
40.300000N 71.300000W c/c_jpg
```

I think https://www.gpsbabel.org/htmldoc-development/fmt_unicsv.html is clear, but if you have suggestions for how to improve the documentation please let us know or submit a PR.
