### ISSUE TITLE
GPX Read error: "Entity 'ntilde' not declared."

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [GPSBabel/gpsbabel#600]
# Problem
I'm merging a lot of gpx files together. I am constantly getting the error `GPX Read error: "Entity 'ntilde' not declared."`

The command I'm using (in this case, with only the file I've attached as a test file. The command is the same with one or more files) is `gpsbabel -i gpx -f downloads/colorado/canon-view-canyon-view.gpx -o gpx -F test.gpx`. The file is not created, the command fails.
[canon-view-canyon-view.zip](https://github.com/gpsbabel/gpsbabel/files/4828241/canon-view-canyon-view.zip)

This error is happening because of encoded characters in the file. In the attached file, the encoded character is in the name element:
```xml
<name>Ca&ntilde;on View (Canyon View)</name>
```

See?

I think gpxbabel needs to convert these to other characters when parsing.

# Bandaid Fix
To unescape the xml characters, run this command on the files you want to run though gpsbabel:
```bash
cat $file | python3 -c 'import html, sys; [print(html.unescape(l), end="") for l in sys.stdin]' > $newfile
```
You might have to re-escape the file because gpsbabel doesn't like the & symbol:
```bash
sed 's/\&/&amp;/g' $file
```

**Comment by tsteven4** [comment]
Your file violates the gpx schema.  This is not a gpsbabel problem.  It is a problem with whatever created canon-view-canyon-view.gpx.
```
Using schemaLocation: "http://www.topografix.com/GPX/1/1 /home/strabert/schema/gpx/gpx11.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 /home/strabert/schema/gpx/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 /home/strabert/schema/gpx/TrackPointExtensionv1.xsd http://www.topografix.com/GPX/1/0 /home/strabert/schema/gpx/gpx10.xsd"

Fatal Error at file canon-view-canyon-view.gpx, line 3, char 27
  Message: entity 'ntilde' not found

Errors occurred, no output available
```

**Comment by Engineer-of-Stuff** [comment]
Ok, but how would you have the letter `Ñ` in a name tag?

**Comment by tsteven4** [comment]
The encoding of the file is declared as UTF-8 in the xml declaration of your file.  The UTF-8 encoding for LATIN SMALL LETTER N WITH TILDE is

UTF-8 (hex) | 0xC3 0xB1 (c3b1)

You can use this directly in your file.

[canon-view-canyon-view-fixed.gpx.zip](https://github.com/gpsbabel/gpsbabel/files/4848791/canon-view-canyon-view-fixed.gpx.zip)

**Comment by robertlipe** [comment]
Right. GPX is fundamentall XML and not HTML. This input file is (slightly)
broken.

**Comment by Engineer-of-Stuff** [comment]
Ok, thanks for the clarification guys.
