### ISSUE TITLE
configurability vs. maintainability

### ISSUE THREAD

**Issue by tsteven4** [GPSBabel/gpsbabel#616]
@viettaml  We think you may be the only user of configure options
  --disable-csv
  --disable-most
  --disable-filters
corresponding to
DEFINES += CSVFMTS_ENABLED
DEFINES += MAXIMAL_ENABLED
DEFINES += FILTERS_ENABLED

Do you use or care about these options and defines?  We are considering removing them from the code as well as configure.
thanks

**Comment by jtojnar** [comment]
I assume this can be closed. `configure` was removed and the options are now always on:

https://github.com/GPSBabel/gpsbabel/blob/8de4c28b6c82e1abbac0df23c68f9c3c82eceee8/CMakeLists.txt#L357-L361

**Comment by robertlipe** [comment]
Tam has bigger problems than this flag when updating us now. Flags removed in
https://github.com/GPSBabel/gpsbabel/pull/1238/

**Comment by robertlipe** [comment]
I did leave the filters flag in case someone wants to build a simplified version behind a GUI, for example.
It wouldn't take much pushing at all to whack that flag, too.
