### ISSUE TITLE
Question:  Ozi codec

### ISSUE THREAD

**Issue by velocat** [GPSBabel/gpsbabel#645]
Installed Gpsbabel in Debian, stable version.
-V = 1.5.7
From which version is the codec argument enabled for the Ozi format ?
It doesn't work for me.
And how to solve this problem?

**Comment by tsteven4** [comment]
The codec option in the ozi format was introduced in gpsbabel version 
1.6.0, so you will need 1.6.0 or 1.7.0.

**Comment by velocat** [comment]
And when are these versions planned to be stable in the Debian repository?

**Comment by tsteven4** [comment]
That's a question for Debian, not us.  You can clone this repo or grab a tarball from http://www.gpsbabel.org/download.html and build from source.

**Comment by velocat** [comment]
Solved. Build and install version 1.7.0

**Comment by robertlipe** [comment]
Be sure and thank them for disabling our built-in upgrade check, too.
