### ISSUE TITLE
Compatibility with FIT 2.0 format

### ISSUE THREAD

**Issue by YousefED** [GPSBabel/gpsbabel#65]
Gpsbabel breaks when provided a 2+ versioned FIT file. I'm not sure how much has changed from version 1 to version 2, but I can provide a couple of sample files if this helps.

Any plans to support the latest fit formats?

**Comment by robertlipe** [comment]
FIT is a reverse engineered format for us. There was a spec published, but
it contained such onerous restrictions that using it in an open source
program wasn't feasible. I haven't reviewed it in the last few years to see
if that's still the case.

You're the first to mention it that I know of and I don't know of anyone
working on an implementation, so if you're planning to do so, let's assign
this to you.

RJL

**Comment by GPSBabelDeveloper** [comment]
Fix committed in https://github.com/gpsbabel/gpsbabel/pull/75
