### ISSUE TITLE
Compiling 1.7.0 on Linux without USB support (./configure --without-libusb) causes compiler error in jeeps/gpsusbstub.cc

### ISSUE THREAD

**Issue by bjkowalski** [GPSBabel/gpsbabel#654]
Using RedHat Enterprise Linux 7.

Downloaded the latest source version 1.7.0 from http://www.gpsbabel.org/download.html.  

Build page recommends to "**yum install qt-develop**" but when attempted "**./configure**" got an error:

`configure: error: Qt qmake (with QT_VERSION >= 5.9) is required but was not found.`

Found that using "**yum install qt5-qtbase-devel**" resolved the QT version issue.

Running "**make**" generated an error:

`g++  -g -O2 -Wall -fPIC -c   -I. -I./zlib -I/usr/include/qt5  -DHAVE_CONFIG_H jeeps/gpsusbstub.cc -o jeeps/gpsusbstub.o
jeeps/gpsusbstub.cc: In function ‘int gusb_init(const char*, gpsdevh**)’:
jeeps/gpsusbstub.cc:37:9: error: ‘Fatal’ was not declared in this scope
   Fatal() << no_usb;
         ^
Makefile:132: recipe for target 'jeeps/gpsusbstub.o' failed
make: *** [jeeps/gpsusbstub.o] Error 1
`

Appears that a change was made to other source files that was missed in jeeps/gpsusbstub.cc.

1.7.0 jeeps/gpsusbstub.cc code is:

`Fatal() << no_usb;`

Resolved by changing to:

`fatal(FatalMsg() << no_usb);`

A different solution already appears to have been made to the current github source. 

You may want to include this as documentation for 1.7.0.

**Comment by richlv** [comment]
Was getting the same error on OpenSUSE Tumbleweed, but as per #655, running qmake-qt5 followed by make resolved it (but it failed later as per #715).

In this issue, the error might be made more clear - although not sure whether there's enough time/interest for that.

**Comment by tsteven4** [comment]
1. the doc is updated with recent Qt package names in #745.
2. yes, there was an error when compiling 1.7.0 without usb support.  Either patch gpsusbstub.cc or install the package (Fedora libusb-devel, Ubuntu libusb-1.0-0-dev.  It was fixed in #610.
