### ISSUE TITLE
Question: Possible to preserve laps when converting fit to tcx?

### ISSUE THREAD

**Issue by khink** [GPSBabel/gpsbabel#668]
Hi, thanks for maintaining GPSBabel! I use it to convert the .fit files my GPS device (Lezyne) generates to convert to .tcx. I then use the tcx file to make graphs (using https://github.com/vkurup/python-tcxparser/. I possibly could have used a Python library like https://github.com/imgrant/fit2tcx for reading the FIT file, but GPSBabel seemed more mature and feature-complete). 

One small thing i noticed: when i convert a fit file with multiple laps in it to tcx, the tcx contains only one lap. Strava does show the laps, so i'm assuming the fit file is not broken. 

The documentation says: "(Training center) deals in concepts like laps and calories, which are rather alien to GPSBabel and most of the formats we support." (https://www.gpsbabel.org/htmldoc-1.5.1/fmt_gtrnctr.html) Does that mean that preserving laps is not going to be possible?

**Comment by robertlipe** [comment]
Our support for laps in general is pretty spotty as it's outside our core goal.  Really, we are interested in converting location more than fitness data, but we do have exceptions when someone wants it badly enough to contribute and support it. It's kind of like things like "camera angle" in a KML file. If you're carrying the KML to another KML, you want to try to keep it, but most other programs have no idea what to do with it, so we don't go to extremes to save these forms of extra data.  From what I can tell, Garmin Fit and Garmin Training Center pretty quickly collapses laps into a track on a read, so we really don't keep them separate.

You could modify your own copy to make each lap a track of its own, but I'm sure that's still a bad fit. We just don't have great infrastructure for this kind of a specialized conversion.

Good luck
