### ISSUE TITLE
DG200 log

### ISSUE THREAD

**Issue by jose1711** [gpsbabel/gpsbabel#810]
Attaching `log.txt` from
`gpsbabel -t -w -D 5 -i dg-200 -f /dev/ttyUSB0 -o gpx -F test.gpx 2>log.txt`
[log.txt.gz](https://github.com/GPSBabel/gpsbabel/files/7808160/log.txt.gz)

Related discussion: https://sourceforge.net/p/gpsbabel/mailman/gpsbabel-misc/thread/c8244409-cc4b-ae43-446f-84c0bb5ee382%40gmail.com/

**Comment by tsteven4** [comment]
Thanks for the log.  I used it to tests @robertlipe's change to show progress, which will be a PR shortly.  However, it turns out another user had submitted ad dg-100 transcript that was used to create a testcase in #558.
