### ISSUE TITLE
AUTHORS, README.contrib duplicated, out of sync

### ISSUE THREAD

**Issue by tsteven4** [gpsbabel/gpsbabel#823]
These files exists in the top level and in the gui subdirectory.  They are picked up by some distributions, e.g. Fedora.

The ones in the top level are more up to date.
Shall we just delete gui/AUTHORS and gui/README.contrib?

**Comment by tsteven4** [comment]
Also, the top level has COPYING, gui has COPYING.txt.  The files are identical.

**Comment by robertlipe** [comment]
Yes, please.
.. and just pick whatever filename is used by, e.g. GCC, Binutils, or other
packages of GNU canon.
