### ISSUE TITLE
GPI file with bitmaps doesn't display properly.

### ISSUE THREAD

**Issue by dpawlyk** [gpsbabel/gpsbabel#827]
GPI file with bitmaps doesn't display properly. They show up as white-ish with a dim outline of item.

Not sure if it's my bitmaps or something else. I was told by the author of GPXSee it was an issue with the palette.

The attached files include the inputs and the command to generate the output.

[BTCNJ-Locations.zip](https://github.com/GPSBabel/gpsbabel/files/7919367/BTCNJ-Locations.zip)

**Comment by tumic0** [comment]
The original issue is here: tumic0/GPXSee#423

**Comment by tsteven4** [comment]
If you give a bitmap we use it for all points when we write the gpi file.  Not that this is what you want, but I did
 ./gpsbabel -i gpx -f "Starts.gpx" -o garmin_gpi,bitmap="poiblockgreen.bmp" -F "starts.gpi"
 ./gpsbabel -i gpx -f "Stops.gpx" -o garmin_gpi,bitmap="poiblockred.bmp" -F "stops.gpi"
with some modified code trying to address the color problem.  @dpawlyk Can you check and see if starts.gpi and stops.gpi display properly?
[gpi.zip](https://github.com/GPSBabel/gpsbabel/files/7921025/gpi.zip)

@tumic0 can you tell me why you always set the high order byte to 0xff in bgr2rgb and rgb(quint32 r, quint32 g, quint32 b)?  I see some old documents that show this extra byte as 0x00, and it appears our code assumed that.

**Comment by tumic0** [comment]
> can you tell me why you always set the high order byte to 0xff in bgr2rgb and rgb(quint32 r, quint32 g, quint32 b)? I see some old documents that show this extra byte as 0x00, and it appears our code assumed that.

Because the formats (where this function is used) do not support the alpha channel, but Qt does in QRgb. A color with the alpha channel set to 0x00 is full transparent regardless of what R,G and B is set to. To get an opaque RGB color in Qt, you have to use 0xFF as the alpha channel.

**Comment by tumic0** [comment]
Btw., the files from gpi.zip are still corrupted, the palette is still not properly written to the file.

**Comment by tsteven4** [comment]
> Btw., the files from gpi.zip are still corrupted, the palette is still not properly written to the file.
Thanks.  Here they are with the extra byte in the palette as zeros.
Unfortunately,  I don't have a way to look at these myself.

[gpialpha0.zip](https://github.com/GPSBabel/gpsbabel/files/7921132/gpialpha0.zip)

**Comment by dpawlyk** [comment]
Those GPI files basically work. The magenta background isn't being treated as transparent though. I wasn't sure if the device would read more than one GPI file (it does).
 
![image](https://user-images.githubusercontent.com/26445864/150693124-30599890-90a1-4909-ae98-a98e75c44b16.png)

Might be useful if one could change the bitmap midstream.

**Comment by tsteven4** [comment]
did you try gpi.zip or gpialpha0.zip?

**Comment by dpawlyk** [comment]
Both look the same.

**Comment by tumic0** [comment]
Still corrupted. You need to write the whole 256 item palette, if you set that palette size in the image header. In your files, only ~40 palette items are written.

**Comment by tsteven4** [comment]
@tumic0 do you have a documentation source for the gpi format that told you how to decode the image information (id, height, width, linesize, bpp, ...) in gpiparser.cc readSymbol?  We don't seem to agree.  I can't defend our interpretation, I am not familiar with the development of our gpi support.

**Comment by tumic0** [comment]
Well, the primary source, as always in case of Garmin, is reverse engineering. So if you have  a Garmin unit, you have the same "documentation" source as I have...

But apart from that "ultimate" format specification, there are many Garmin produced GPI files out there which all have it right and even 3rd party SW that produces GPI files that also write correct GPI files. In some cases even GPSBabel writes valid GPI files (depending on the image) but not always...

**Comment by tsteven4** [comment]
@tumic0 thanks for you insight.
I reduced the "palette size" in the image header to match the # of written palette items.  Our reverse engineering effort long ago in history called it "flag1", evidently we didn't really know what it was.

[try3.zip](https://github.com/GPSBabel/gpsbabel/files/7921231/try3.zip)

**Comment by tumic0** [comment]
Now it works. Only the transparency is broken, but that is because of the images, that have the "transparent" color set to 0xDC00FF instead of 0xFF00FF.

**Comment by dpawlyk** [comment]
Is that from my bitmaps?

**Comment by tumic0** [comment]
> Is that from my bitmaps?

yes, look at them in some image editor like Gimp and you will see, that the magenta borders are in fact not "real" magenta.

**Comment by tsteven4** [comment]
BTW this in process fix missed our 1.8.0 release by four days.  However, we still don't support using different bitmaps for different points.

**Comment by dpawlyk** [comment]
Not a real problem that it missed the last release. That it will get out sometime is good enough.

The multiple bitmaps is a "might be nice" feature.

Thanks.

**Comment by tumic0** [comment]
Even with the old and broken GPSBabel versions you can produce valid GPI files with symbols - you just have to use images with a full 256 color palette.

**Comment by tsteven4** [comment]
yes.  thanks for your help @tumic0.

**Comment by dpawlyk** [comment]
Alas, on Garmins that I've tried (1030+, 1000), the two files don't work. Two categories show up but the names are repeated and the POIs from the second file show up as blank.

**Comment by tumic0** [comment]
Well, I was a little bit afraid this can happen. This is why I would rather fix the issue by always writing the full 256 items palette, than to write it only partially and set the palette size. While it is clear, that the original implementation is broken - if you do not write the palette size and write only a variable size palette, how can the reader know, how many items to read? - it is not clear if ALL Garmin SW can handle partial palettes (we only know, that some of their SW can do that). And evidently it does not.

There may of course be another problem with the files, I have no idea what all has been changed when producing those two GPI files, but the patch does not seem to alter much more...

**Comment by dpawlyk** [comment]
**Never mind.** The files in gpialpha0.zip (attached above) work fine. They have the same category (which shows up twice).

The files produced by the current version of GPSBabel don't work together (but we don't really care about that any longer).

**Comment by tumic0** [comment]
Ok, that's something completely different, if the files do not work together (but work separate). That will be caused by the clash of the category/symbol ids.

**Comment by dpawlyk** [comment]
I think it won't be a problem with the future version of GPS Babel.

**Comment by tsteven4** [comment]
Does using the category option allow the files to work together?

./gpsbabel -i gpx -f Starts.gpx -o garmin_gpi,bitmap=poiblockgreen.bmp,category=Starts -F Starts.gpi
./gpsbabel -i gpx -f Stops.gpx -o garmin_gpi,bitmap=poiblockred.bmp,category=Stops -F Stops.gpi

**Comment by dpawlyk** [comment]
I don't think there's a problem _unless_ you are using a bitmap (like the ones I'm using) with the current version of GPSBabel. The files you provided (using the updated version of GPSBabel) above work properly.

On a different/unrelated topic...

POI Loader lets you create a single file (with multiple bitmaps and categories).

**Comment by tsteven4** [comment]
Here are the files when I specify the categories "Starts" and "Stops" as I described above.
[try4.zip](https://github.com/GPSBabel/gpsbabel/files/7933844/try4.zip)
Does this resolve

> Alas, on Garmins that I've tried (1030+, 1000), the two files don't work. Two categories show up but the names are repeated and the POIs from the second file show up as blank.

**Comment by dpawlyk** [comment]
Yes, those files work.
