### ISSUE TITLE
Move the Development Discussions from mailing list to Github on the website Help page

### ISSUE THREAD

**Issue by maximecharriere** [gpsbabel/gpsbabel#879]
In the [Development Discussions](https://www.gpsbabel.org/lists.html) section of the gpsbabel.org website, it's said to use the Mailing list, but now gpsbabel use Github issue.  

Shouldn't this info be changed?

**Comment by robertlipe** [comment]
No. Email is still preferred. The trend this week of people tagging onto
closed issues (which creates more work for us to then go declutter) is an
unsustainable one.

If we could disable the Github thing, we would.

RJL

**Comment by maximecharriere** [comment]
Oh okay, sorry. My bad.
