### ISSUE TITLE
RE: Working w/ Google Earth/Desktop

### ISSUE THREAD

**Issue by silver2row** [GPSBabel/gpsbabel#92]
Hello,

I am new to your org and want to find out more. If I was to add a file and change the format with your software, could I view it in an external application, i.e. like Google Earth?

I am asking because I have tried before with your software and I cannot get it "tweaked" just right.

Seth

P.S. I have a kml file and/or .txt file and I do not know which file to choose to change into another file type. Sorry for this inexperienced question.

**Comment by robertlipe** [comment]
Hi, and welcome.

Best I can understand your question, it's "can I use GPSBabel to write
files that Google Earth can read?" The answer is "yes" - our KML writer is
the heart of most of Earth's file imports.

https://www.gpsbabel.org/htmldoc-development/fmt_kml.html
