### ISSUE TITLE
Setting Garmin TCX files as input, .tcx files cannot be selected

### ISSUE THREAD

**Issue by habi** [GPSBabel/gpsbabel#96]
Sometimes it's nice to use the GUI instead of typing the correct filenames in the terminal command `gpsbabel -i gtrnctr -f ~/input.tcx -o gpx -F ~/output.gpx`.

But the GUI doesn't let me select .tcx files when I ask it to get files with the format 'Garmin Training Center (.tcx)', as seen in the attached screenshot.

![screen shot 2017-11-01 at 20 51 31](https://user-images.githubusercontent.com/1651235/32294814-a4cac2b0-bf47-11e7-8a60-6f9fa7c39a26.PNG)

GPSBabel GPSBabel 1.5.4 on OS X 10.12.6 (16G29).

**Comment by tsteven4** [comment]
pull request #149 should resolve the issue you reported.  Thanks for reporting it.  By default Garmin Training Center conversions will look for .tcx, .crs, .hst and .xml files.

Note that in the GPSbabel file dialog "Select one or more input files" if you click on the box "Garmin Training Center ..." above the Open and Cancel buttons you can select "All files (*.*)".  This won't be necessary after the PR.

**Comment by habi** [comment]
Thanks!
