### ISSUE TITLE
garmin, ozi, xcsv mkshort options whitespace_ok, must_unique broken since 2006

### ISSUE THREAD

**Issue by tsteven4** [gpsbabel/gpsbabel#982]
I think https://github.com/GPSBabel/gpsbabel/commit/75a4b039b broke these options by adding the logic in vecs noted by
`/* for bool options without default: don't set argval if "FALSE" */`

at that time, as today, mkshort_new_handle set both options to 1 (true).

garmin.c, ozi.c and xcsv.c wouldn't call setshort_whitespace_ok or setshort_mustuniq if the option value was null.  They all used bool options without a default.  Therefore, it was impossible to use those options to set whitespace_ok to false or must_unique to false.

If so this went undiscovered for 16 years.  This suggest to me these options can be removed from these formats instead of fixed.

The option must_upper defaulted to 0 in mkshort_new_handle.  Therefore the format options to set this could have worked.  I have verified that they don't work today with ozi and xcsv.  I haven't verified that the above commit broke them, or that they stayed broken for every release since then.

I would propose removing the format options for whitespaceok and must_unique from garmin, ozi and xcsv.  We could further consider removing the option for must_upper, although that worked and could be in use.

**Comment by tsteven4** [comment]
I was able to rebuild 1.6.0 (2019) and verify the non-functionality of those two options with ozi and xcsv.

**Comment by tsteven4** [comment]
I was also able to build 1.5.4 (2017), with a few tweaks, and verify the same non-functionality.

**Comment by GPSBabelDeveloper** [comment]
Agreed. After even five years,. It's not a bug; it's a feeeeeature.

**Comment by tsteven4** [comment]
@robertlipe 
Specifically I propose to delete
ozi snwhite, snunique and snupper*
garmin snwhite
xcsv snwhite, snunique and snupper*
options.

The snupper* options did work, so the lack of a need for them is unproven.  I contend the others have been ignored worked for 16 years.

**Comment by robertlipe** [comment]
I agree. These are sensible defaults. We probably should have never exposed
knobs for these.

Changing xcsv is always scary as it trickles to so many (often obscure and
rarely testable for us) formats, but since anything using it has used these
settings for so many years, I agree.

Launch codes verified. Execute at your call.

**Comment by robertlipe** [comment]
@tsteven4 , what do you think about #1239 ? I tagged it as needing a release note.

**Comment by tsteven4** [comment]
I'm ok with the idea, but #1239 has a bunch of merge conflicts.

**Comment by robertlipe** [comment]
I think my work tree is just corrupt. It's time to just rm -fr it and check
out a new working copy. I'm getting merge conflicts in code that's not been
touched in years that doesn't show up on a diff or even after I first
commit it.

Though I admit to having a strained relationship with Git, it does not fill
me with love and confidence. :-/

I'll work through that separately, though it may be a bit with the holidays.

**Comment by tsteven4** [comment]
#1239 looks like a bad merge.  Sorry, I have touched a ton of stuff in the last week converting the last formats to Format class, including garmin.

**Comment by robertlipe** [comment]
That was a fresh pull from head  and a branch created last night. I edited
that merge conflict (like 4 - 5 files) on the web and got 418 changed
files. Clearly my git repo is screwed up somewhere.
