### ISSUE TITLE
Light gpsbabel for CI/CD

### ISSUE THREAD

**Issue by ybert** [gpsbabel/gpsbabel#985]
We use GPSBabel for our project and we would like to include it in our CI/CD Pipeline to do unit tests on a PHP software that use gpsbabel command.

The problem is  if we install GPS Babel from alpine linux, we need QT5 installed on it. And QT5 is heavy (500MB).
Our build and test docker pipeline which was 100MB now weighs 550MB and it become very slow to load.

Is there any way to build gpsbabel and have a standalone gpsbabel binary with all needed in it  ?
Thanks in advance for your help !

**Comment by robertlipe** [comment]
GPSBabel requires Qt. Just look at the source for, say, QString or QDate.
We use it extensively, even in the command line version. You can't
just configure it away.

This is not new. It's been true for many years.

You can use prebuilt libraries instead of bootstrapping qt or just install
qt-devel (or whatever your distro calls it) and that should be quick as it
should be just a few file copies.

**Comment by tsteven4** [comment]
It sounds like you are installing much more than is needed.  The command line client, gpsbabel, only uses libQt5Core or libQt6Core and libQt6Core5Compat.  These dependencies are about 7MB.  The GUI, gpsbabelfe, needs much more of Qt.

It is unclear what "install GPS Babel from alpine linux" entails to me, but I think it is installing much more than is needed to execute the CLI gpsbabel.

**Comment by ybert** [comment]
Thanks for your answers.

I just installed qt5-qtbase-dev, but it has many dependencies which are not included in base alpine linux.
Alpine Linux is a lightweight distribution very often used in docker images for CI/CD as it is only 3.5MB download.

So with just qt5-qtbase-dev and all its dependencies the image weight increase by 400MB.

**Comment by robertlipe** [comment]
YOu should probably just cache a binary version that's built with flags to your taste.

We have no influence on how Alpine is packaged. Sorry.
