### ISSUE TITLE
Emphasize interpolation not a great circle

### ISSUE THREAD

**Issue by jidanni** [gpsbabel/gpsbabel#991]
The GPSbabel interpolation documentation perhaps should mention that yes  such straight line interpolation might not be  best for airplane routes, which are often great circles.

C.f. https://github.com/dfandrich/gpscorrelate/pull/21

**Comment by tsteven4** [comment]
The interpolation filter does creates points along a great circle, but planes may not go along it.
![image](https://user-images.githubusercontent.com/13596209/213713518-5805abeb-dc93-48ec-9a5a-b8ac318d6a42.png)
The image shows an interpolated track between Tokyo and San Francisco along with your FlightAware track.

**Comment by jidanni** [comment]
I see. Okay, then it is even more important to mention that the interpolations are great circles, because one would  expect straight lines... I mean simple linear interpolation.

https://www.quora.com/Are-airplanes-great-circle-routes-always-actually-just-a-series-of-straight-segments-e-g-20-to-cross-the-Pacific

Okay, all this is getting over my head.
